image: alpine:latest

stages:
- deploy

deploy:
  stage: deploy

  environment:
    name: production

  before_script:
  - wget -qO /usr/local/bin/skaffold https://storage.googleapis.com/skaffold/releases/v0.33.0/skaffold-linux-amd64
  - wget -qO /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
  - wget -qO /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v2.0.3/kustomize_2.0.3_linux_amd64
  - chmod +x /usr/local/bin/skaffold /usr/local/bin/kubectl /usr/local/bin/kustomize
  - apk add git maven openjdk8
  - mkdir ~/.docker/
  - |
    cat - > ~/.docker/config.json <<EOF
    {
      "auths": {
        "$CI_REGISTRY": {
          "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
        }
      }
    }
    EOF

  only:
  - master
  - tags

  script:
  - skaffold run
