/*
 * generated by Xtext 2.18.0
 */
package com.zazuko.apitesting.dsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class CoreWebModule extends AbstractCoreWebModule {
}
