/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl

import org.eclipse.xtext.conversion.IValueConverterService
import app.hypermedia.testing.dsl.conversion.CoreValueConverterService
import com.google.inject.Binder
import org.eclipse.xtext.parser.IEncodingProvider
import org.eclipse.xtext.service.DispatchingProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CoreRuntimeModule extends AbstractCoreRuntimeModule {
    override Class<? extends IValueConverterService> bindIValueConverterService() {
        return CoreValueConverterService
    }

    override configureRuntimeEncodingProvider(Binder binder) {
        binder.bind(IEncodingProvider)
              .annotatedWith(DispatchingProvider.Runtime)
              .to(AlwaysUtfEncodingProvider)
    }
}
