/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CoreRuntimeModule extends AbstractCoreRuntimeModule {
}
