/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HydraStandaloneSetup extends HydraStandaloneSetupGenerated {

    def static void doSetup() {
        new HydraStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
