apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hypertest
spec:
  rules:
  - host: hypertest.kube.zazuko.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hypertest
          servicePort: 80
