/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.web

import com.google.inject.Guice
import com.google.inject.Injector
import app.hypermedia.testing.dsl.CoreRuntimeModule
import app.hypermedia.testing.dsl.CoreStandaloneSetup
import app.hypermedia.testing.dsl.ide.CoreIdeModule
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages in web applications.
 */
class CoreWebSetup extends CoreStandaloneSetup {

    override Injector createInjector() {
        return Guice.createInjector(Modules2.mixin(new CoreRuntimeModule, new CoreIdeModule, new CoreWebModule))
    }

}
