/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.web

import app.hypermedia.testing.dsl.HydraRuntimeModule
import app.hypermedia.testing.dsl.HydraStandaloneSetup
import app.hypermedia.testing.dsl.ide.HydraIdeModule
import com.google.inject.Guice
import com.google.inject.Injector
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages in web applications.
 */
class HydraWebSetup extends HydraStandaloneSetup {
	
	override Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HydraRuntimeModule, new HydraIdeModule, new HydraWebModule))
	}
	
}
