/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.ide

import com.google.inject.Guice
import app.hypermedia.testing.dsl.CoreRuntimeModule
import app.hypermedia.testing.dsl.CoreStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CoreIdeSetup extends CoreStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CoreRuntimeModule, new CoreIdeModule))
	}
	
}
