/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.validation

import app.hypermedia.testing.dsl.core.StatusStatement
import app.hypermedia.testing.dsl.core.CorePackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class CoreValidator extends AbstractCoreValidator {

    @Check
    def checkStatusIsWithinRange(StatusStatement statusStatement) {
        if (statusStatement.status < 100 || statusStatement.status > 599) {
            error('Status can be an integer between 100 and 599',
                  CorePackage.Literals.STATUS_STATEMENT__STATUS)
        }
    }
}
