/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class CoreScopeProvider extends AbstractCoreScopeProvider {

}
