/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(CoreInjectorProvider)
class CoreParsingTest {
	// keep this around because it's regenerated by mwe2
}
