/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.tests

import com.google.inject.Inject
import app.hypermedia.testing.dsl.core.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import static org.junit.Assert.assertEquals
import app.hypermedia.testing.dsl.core.ClassBlock

@ExtendWith(InjectionExtension)
@InjectWith(CoreInjectorProvider)
class CoreParsingTest {
    @Inject
    ParseHelper<Model> parseHelper
	
    @Test
    def void withClass_ParsesName() {
        // when
        val result = parseHelper.parse('''
            With Class "Foo" {
				
            }
        ''')
		
        // then
        TestHelpers.assertModelParsedSuccessfully(result)
		
        val classBlock = result.elements.get(0) as ClassBlock
        assertEquals(classBlock.name, "Foo")
    }
}
