/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.tests

import app.hypermedia.testing.dsl.core.ClassBlock
import app.hypermedia.testing.dsl.core.CoreScenario
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import app.hypermedia.testing.dsl.core.PropertyBlock
import app.hypermedia.testing.dsl.core.PropertyStatement
import static org.assertj.core.api.Assertions.*;
import app.hypermedia.testing.dsl.core.StringValue
import app.hypermedia.testing.dsl.core.IntValue
import app.hypermedia.testing.dsl.core.BooleanValue
import app.hypermedia.testing.dsl.core.DecimalValue

@ExtendWith(InjectionExtension)
@InjectWith(CoreInjectorProvider)
class PropertyParsingTest {
    @Inject
    ParseHelper<CoreScenario> parseHelper

    @Test
    def void withProperty_parsesName() {
        // when
        val result = parseHelper.parse('''
            With Class "Person" {
                With Property "name" {
                }
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyBlock = classBlock.children.get(0) as PropertyBlock
        assertThat(propertyBlock.name.value).isEqualTo("name")
    }

    @Test
    def void expectProperty_parsesWithoutChildren() {
        // when
        val result = parseHelper.parse('''
            With Class "Person" {
                Expect Property "name"
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStmt = classBlock.children.get(0) as PropertyStatement
        assertThat(propertyStmt.name.value).isEqualTo("name")
    }

    @Test
    def void expectProperty_parsesOptionalValueToAssert() {
        // when
        val result = parseHelper.parse('''
            With Class "Person" {
                Expect Property "name" "TOMASZ"
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStmt = classBlock.children.get(0) as PropertyStatement
        assertThat((propertyStmt.expectation as StringValue).value).isEqualTo("TOMASZ")
    }

    @Test
    def void withProperty_parsedSuccessfullyWithChildren() {
        // when
        val result = parseHelper.parse('''
            With Class "Book" {
                With Property "author" {
                    Expect Property "name"
                }
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyBlock = classBlock.children.get(0) as PropertyBlock
        assertThat(propertyBlock.children.length).isEqualTo(1)
        assertThat(propertyBlock.children.get(0)).isInstanceOf(PropertyStatement)
    }

    @Test
    def void withProperty_parsingFailsWhenItHasNoChildren() {
        // when
        val result = parseHelper.parse('''
            With Class "Book" {
                With Property "author"
            }
        ''')

        // then
        TestHelpers.assertModelParsingFailed(result)
    }

    @Test
    def void expectProperty_succesfullyParsesInt() {
        // when
        val result = parseHelper.parse('''
            With Class "Book" {
                Expect Property "pageCount" 1098
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStatement = classBlock.children.get(0) as PropertyStatement
        assertThat(propertyStatement.expectation).isInstanceOf(IntValue)
    }

    @Test
    def void expectProperty_succesfullyParsesBoolean() {
        // when
        val result = parseHelper.parse('''
            With Class "Book" {
                Expect Property "read" false
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStatement = classBlock.children.get(0) as PropertyStatement
        assertThat(propertyStatement.expectation).isInstanceOf(BooleanValue)
    }

    @Test
    def void expectProperty_succesfullyParsesDecimal() {
        // when
        val result = parseHelper.parse('''
            With Class "Book" {
                Expect Property "price" 10.99
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStatement = classBlock.children.get(0) as PropertyStatement
        assertThat(propertyStatement.expectation).isInstanceOf(DecimalValue)
    }
}
