/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.tests.hydra

import app.hypermedia.testing.dsl.hydra.OperationBlock
import app.hypermedia.testing.dsl.core.Model
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import static org.junit.Assert.assertEquals
import app.hypermedia.testing.dsl.tests.HydraInjectorProvider
import static org.assertj.core.api.Assertions.*
import app.hypermedia.testing.dsl.hydra.InvocationBlock
import app.hypermedia.testing.dsl.tests.TestHelpers

@ExtendWith(InjectionExtension)
@InjectWith(HydraInjectorProvider)
class OperationParsingTest {
    @Inject
    ParseHelper<Model> parseHelper

    @Test
    def void withOperationOnTopLevel_ParsesName() {
        // when
        val result = parseHelper.parse('''
            With Operation "CreateUser" {

            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)
        
        val classBlock = result.steps.get(0) as OperationBlock
        assertEquals(classBlock.name, "CreateUser")
    }

    @Test
    def void withOperationOnTopLevelWithInvocation_ParsesSuccessfully() {
        // when
        val result = parseHelper.parse('''
            With Operation "CreateUser" {
                Invoke {
                }
                
                Invoke {
                }

                Invoke {
                }
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)
        
        val operationBlock = result.steps.get(0) as OperationBlock
        assertThat(operationBlock.invocations).hasSize(3)
        val invokeBlock = operationBlock.invocations.get(0)
        assertThat(invokeBlock).isInstanceOf(InvocationBlock)
    }
}
