name: Build and push Docker image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Login to GitHub Container Registry
        if: github.repository == 'hypermedia-app/hypertest'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        if: github.repository == 'hypermedia-app/hypertest'
        uses: zazuko/action-docker-meta@main
        id: docker_meta
        with:
          images: ghcr.io/hypermedia-app/hypertest

      - name: Build package
        run: mvn package

      - name: Build and push Docker image
        if: github.repository == 'hypermedia-app/hypertest'
        run: |
          imgs="${{ steps.docker_meta.outputs.tags }}"
          OLD_IFS=$IFS
          IFS=","
          for img in $imgs; do
            mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build "-Dimage=${img}"
          done
          IFS=$OLD_IFS
